name: "test"

on:
  pull_request:
    paths-ignore:
      - "!**.md"
  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  fluence-cli:
    uses: ./.github/workflows/tests.yml
    strategy:
      matrix:
        include:
          - platform: win32-x64
            runner: windows-amd64-m-2xlarge
          - platform: linux-x64
            runner: linux-amd64-m-2xlarge
    with:
      ref: ${{ github.ref }}
      runner: ${{ matrix.runner }}
      platform: ${{ matrix.platform }}
